### PR TITLE
fixed placeholder color

### LINKED ISSUE #3: The Placeholder text does not suit the theme of the web application
The placeholder text should not be grey because it is not visible. There should be dark grey background on the text input for city. The text should be  white

### PR DESCRIPTION
**Pull request by xit4**
fixes #3

### CODE REVIEW

**Comment by sandeep-v1404** [comment]
Fix the merge conflicts @xit4

**Comment by xit4** [comment]
@sandeep-v1404 done!

**Comment by sandeep-v1404** [comment]
@xit4 Fix Conflicts

**Comment by xit4** [comment]
@sandeep-v1404 done again! :P

**Pull request merged**
